CREATE TABLE `receipts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`imageKey` varchar(512) NOT NULL,
	`imageUrl` text NOT NULL,
	`merchantName` varchar(256),
	`transactionDate` timestamp,
	`amount` decimal(18,2),
	`currency` varchar(8) DEFAULT 'CAD',
	`category` varchar(64),
	`description` text,
	`rawText` text,
	`aiConfidence` decimal(5,2),
	`transactionId` int,
	`bankAccountId` int,
	`status` enum('pending','confirmed','rejected') NOT NULL DEFAULT 'pending',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `receipts_id` PRIMARY KEY(`id`)
);
